### PR TITLE
Employee list

### PR DESCRIPTION
**Pull request by vaishsh**

### CODE REVIEW

**Comment by vaishsh** [comment]
These are partial changes.
I will continue working once we move the remote to copartit.

**Comment by Aldizh** [comment]
Can you please remove _package-lock.json_ file

**Comment by nikhilnarula** [comment]
And also yarn.lock.

For some reason, I am not able to add review comments. In file ‘src/store/constants/employees.js<https://github.com/Aldizh/employee/pull/4/commits/37d5a73acab1ed4e6e00b421114ff0f481f55b44#diff-fe42c5066396d5270cbd1d8a31d909c1>’, you are have a type at line 28 - SAVE_LIST_DISPLAY = 'SAVE_LIST_DISPLAY'?

**Comment by vaishsh** [comment]
Ideally package-lock.json and yarn.lock, both should be commited in the project folder.
package-lock.json gets generated through npm 5, and can be removed because we use yarn as package manager.  We should keep yarn.lock to have consistent dependency versions for other users.

**Comment by nikhilnarula** [comment]
Cool!

**Pull request merged**
